// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe69n5gh_5UbMEieKn5LUZeF3QYUiJhDg',
    appId: '1:701759229006:web:206c3c05ad822070a7871f',
    messagingSenderId: '701759229006',
    projectId: 'coderman-283dc',
    authDomain: 'coderman-283dc.firebaseapp.com',
    storageBucket: 'coderman-283dc.firebasestorage.app',
    measurementId: 'G-LCQVQKSW8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXBa3tl9G0Y7AO9bvBoLjGUog_0_6qHFk',
    appId: '1:701759229006:android:11a63a0651d52d82a7871f',
    messagingSenderId: '701759229006',
    projectId: 'coderman-283dc',
    storageBucket: 'coderman-283dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmtoktHEUd1Owdp59LXG0yU9_yhCX5Nw',
    appId: '1:701759229006:ios:ccdb9c5a8a01b1aea7871f',
    messagingSenderId: '701759229006',
    projectId: 'coderman-283dc',
    storageBucket: 'coderman-283dc.firebasestorage.app',
    iosBundleId: 'com.coderman.coderman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmtoktHEUd1Owdp59LXG0yU9_yhCX5Nw',
    appId: '1:701759229006:ios:ccdb9c5a8a01b1aea7871f',
    messagingSenderId: '701759229006',
    projectId: 'coderman-283dc',
    storageBucket: 'coderman-283dc.firebasestorage.app',
    iosBundleId: 'com.coderman.coderman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe69n5gh_5UbMEieKn5LUZeF3QYUiJhDg',
    appId: '1:701759229006:web:6146bcd4b66bd6f4a7871f',
    messagingSenderId: '701759229006',
    projectId: 'coderman-283dc',
    authDomain: 'coderman-283dc.firebaseapp.com',
    storageBucket: 'coderman-283dc.firebasestorage.app',
    measurementId: 'G-ND3C5CB0KE',
  );
}
